type User {
  id: ID!
  name: String
  email: String
  phoneNumber: String
}

input CreateUserInput {
  name: String!
  email: String!
  phoneNumber: String!
}

input UpdateUserInput {
  id: ID!
  name: String
  email: String
  phoneNumber: String
}

input DeleteUserInput {
  id: ID!
}

type Query {
  user(id: ID!): User!
}

type Mutation {
  createUser(input: CreateUserInput!): User
  updateUser(input: UpdateUserInput!): User
  deleteUser(id: ID!): User
}
